# Site config
title: Daily LeetCode in JS
description: >- # this means to ignore newlines until "baseurl:"
  Going through the LeetCode question of the day in javascript for the whole year (2023).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shadow_stack
github_username: leabs

# Pagination
paginate: 31
paginate_path: "/blog/page:num/"

# Theme settings
theme: minima
minima:
  skin: solarized

# Syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false

# Allow future posts
future: true

#Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# SEO
twitter:
  username: shadow_stack
  card: summary
